# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1.2
loader_version=0.19.2
loom_version=1.15-SNAPSHOT

# Mod Properties
mod_version=2.0.0+refabricated-26.1.2
maven_group=com.davigj
archives_base_name=frame_changer

# Dependencies
fabric_version=0.146.0+26.1.2